pipeline {
    agent {
        label "devops"
    }
    stages{
        stage("build Docker Image"){
            steps {
                sh "docker build -t myphpimg ."
            }
        }
        stage("Image Push"){
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockercreds',usernameVariable: 'docker_user', passwordVariable: 'docker_pass')]){
                    sh "docker tag static ${env.docker_user}/static:${BUILD_NUMBER}"
                    sh "docker login -u ${env.docker_user} -p ${env.docker_pass}"
                    sh "docker push ${env.docker_user}/static:${BUILD_NUMBER}" 
                }
            }
        }
    }
}