pipeline {
    agent { label 'devops' }

    stages {
        stage('Build Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockercreds',
                    usernameVariable: 'docker_user',
                    passwordVariable: 'docker_pass'
                )]) {
                    sh '''
                        docker build -t ${docker_user}/static:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockercreds',
                    usernameVariable: 'docker_user',
                    passwordVariable: 'docker_pass'
                )]) {
                    sh '''
                        set -e
                        echo "$docker_pass" | docker login -u "$docker_user" --password-stdin
                        docker push ${docker_user}/static:${BUILD_NUMBER}
                    '''
                }
            }
        }
    }
}
